/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CommentInator {
        "groupId": string;
        "height": string;
    }
}
declare global {
    interface HTMLCommentInatorElement extends Components.CommentInator, HTMLStencilElement {
    }
    var HTMLCommentInatorElement: {
        prototype: HTMLCommentInatorElement;
        new (): HTMLCommentInatorElement;
    };
    interface HTMLElementTagNameMap {
        "comment-inator": HTMLCommentInatorElement;
    }
}
declare namespace LocalJSX {
    interface CommentInator {
        "groupId"?: string;
        "height"?: string;
    }
    interface IntrinsicElements {
        "comment-inator": CommentInator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "comment-inator": LocalJSX.CommentInator & JSXBase.HTMLAttributes<HTMLCommentInatorElement>;
        }
    }
}
