name: Deploy Docs

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: yarn install
      working-directory: ./docs

    - name: Build Docs
      run: yarn build
      working-directory: ./docs

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build 

    # - name: Clean up
    #   run: rm -rf docs/build  # Adjust the path based on your project structure
